### ISSUE TITLE
dropping Copy impl for Config/Instructions in 5.2.0 breaks semver guarantees

### ISSUE THREAD

**Issue by decathorpe** [rustyhorde/vergen#96]
It looks like the `Copy` trait is no longer derived for `Instructions` since version 5.2.0, as of this commit:
https://github.com/rustyhorde/vergen/commit/5f298359a4189a4cd8c04bfc97b544ed8d057f26

The `Copy` trait impl is also gone from the documentation:

- 5.1.17 has it: https://docs.rs/vergen/5.1.17/vergen/struct.Config.html
- 5.2.0 doesn't: https://docs.rs/vergen/5.2.0/vergen/struct.Config.html

Dropping a trait impl for a public trait is a SemVer-incompatible change, since it *removes* an API that was previously there (although implicitly). In this case, because it makes a type that was previously a copy-type a move-type.

I have now seen multiple crates that fail to compile after updating from vergen 5.1.17 to 5.2.0, with errors similar to this one:

```
error[E0382]: borrow of moved value: `config`
  --> /usr/share/cargo/registry/rd-util-2.1.2/build.rs:11:14
   |
5  |     let mut config = Config::default();
   |         ---------- move occurs because `config` has type `Config`, which does not implement the `Copy` trait
...
8  |     match vergen(config) {
   |                  ------ value moved here
...
11 |             *config.git_mut().enabled_mut() = false;
   |              ^^^^^^^^^^^^^^^^ value borrowed here after move
For more information about this error, try `rustc --explain E0382`.
```

(error message from build of https://crates.io/crates/rd-util ; also affects builds of all dependent crates)

**Comment by jasonozias** [comment]
You are correct.  I was hoping to avoid creating a 6.0 release for this change, but it looks like this needs to happen as the API did break.  In the meantime, I would specify a specific version (5.1.17) in your config to avoid this issue.   I'll get a 6.0 release ready with some docs on the breaking change in the meantime.

**Comment by jasonozias** [comment]
Release 6.0.0 created, docs updated and 5.2.0 yanked.   Let me know if you have any additional issues.

**Comment by decathorpe** [comment]
Thanks!
