### ISSUE TITLE
Vergen failing to compile as dependency when updating to 8.2.3 from 8.2.1

### ISSUE THREAD

**Issue by YJDoc2** [rustyhorde/vergen#225]
Recently dependabot tried to update vergen in a project from 8.2.1 to 8.2.3. It is failing at compile stage with error 
```sh
   Compiling vergen v8.2.3
error[E0599]: no method named `checked_to_offset` found for struct `OffsetDateTime` in the current scope
   --> .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/vergen-8.2.3/src/feature/git/cmd.rs:651:54
    |
651 |                         let local_offset = no_offset.checked_to_offset(local).unwrap_or(no_offset);
    |                                                      ^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `to_offset`

```

The vergen dependency in cargo.tom is `vergen = {version ="8.2.1", features =["git","gitcl"]}`.

The dependabot PR on which this is failing is https://github.com/containers/youki/pull/2111 actual CI https://github.com/containers/youki/actions/runs/5451984710/jobs/9918894204?pr=2111

I also tried building locally and it fails with the same error.
Is there some config issue such as feature selection issue from my side, or anything else?

Thanks!

**Comment by JamesHinshelwood** [comment]
[`OffsetDateTime::checked_to_offset`](https://docs.rs/time/latest/time/struct.OffsetDateTime.html#method.checked_to_offset) was added to `time` in `v0.3.22`, but `vergen` only declares a dependency on `v0.3.20`.

We should be able to fix this with a `cargo update` to update the versions of transient dependencies, but we should also probably declare the correct version in `vergen`.

**Comment by YJDoc2** [comment]
I'm curious, would this require the vergen 8.2.3 be yanked, or just a bump? Not sure how semvar would/should work with this :thinking:

**Comment by CraZySacX** [comment]
I will yank `8.2.3`.  Although this isn't technically a problem with `vergen` as updating transient dependencies will fix the issue, I'd rather make it less hassle.  As soon as the PR @JamesHinshelwood has created passes through the pipelines, I will create `8.2.4`.

**Comment by YJDoc2** [comment]
@JamesHinshelwood Thanks for the quick triaging and opening the PR. @CraZySacX thanks for the quick update and release :)
